version: '3'
services:
  web_assistente:
    image: albreis/assistente
    build: .
    ports:
      - 8087:80
    env_file:
      - .env
    volumes:
      - ./:/var/www/html # Mapeia o diretório do seu código PHP para o diretório do Apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html # Define o diretório raiz do Apache para o seu código